export const Data = [
  {
    id: "1",
    title: "Member Only Live Replay Sulianto & Quant, 5 Juni 2025",
    drive: "https://youtu.be/RLvC8K-qTeI?si=VZZx89aqRFQNB-IV",
    link: "/Halaman/page/3/10/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Member Only Live Replay Quant, 18 Juni 2025",
    drive: "https://youtu.be/eIUyel7ymEY?si=wSqdQpmnxqL6ZvF5",
    link: "/Halaman/page/3/10/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Member Only Live Replay Quant, 23 Juni 2025",
    drive: "https://youtu.be/y8hNP_qEbNc?si=OuOCNoWz6w7Id2qU",
    link: "/Halaman/page/3/10/3",
    category: "Member Only Live Replay",
  },
  {
    id: "4",
    title: "Member Only Live Replay Quant, 25 Juni 2025",
    drive: "https://youtu.be/GD7kSeNFyYE?si=gEelOD0b8psGkEuX",
    link: "/Halaman/page/3/10/4",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Quant Live 11 Juli 2025 - Bitcoin ATH Market Update",
    drive: "https://youtu.be/Qi_5jrJlwX8?si=IrU7HgliBRdi23FA",
    link: "/Halaman/page/3/10/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Quant Live 13 Juli 2025 - Bitcoin ATH Market Update",
    drive: "https://youtu.be/wbnCPbmx5Do?si=uYTGHDHz0kIjjfHO",
    link: "/Halaman/page/3/10/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Quant Live 15 Juli 2025",
    drive: "https://youtu.be/ktJvkZVyXwE?si=xmaVmY7iuL_TCsKV",
    link: "/Halaman/page/3/10/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Quant Live 16 Juli 2025",
    drive: "https://youtu.be/d3bXvFCkMl0?si=IeEKIpJV_oGmjcvQ",
    link: "/Halaman/page/3/10/8",
    category: "Member Only Live Replay",
  },
  {
    id: "9",
    title: "Quant Live 19 Juli 2025",
    drive: "https://youtu.be/W9pUM5xhiSA?si=F8lVZqCothSe6kqW",
    link: "/Halaman/page/3/10/9",
    category: "Member Only Live Replay",
  },
  {
    id: "10",
    title: "Quant Live 23 Juli 2025",
    drive: "https://youtu.be/OtRHuCq4yY8",
    link: "/Halaman/page/3/10/10",
    category: "Member Only Live Replay",
  },
  {
    id: "11",
    title: "Quant Live 24 Juli 2025",
    drive: "https://youtu.be/LRcJjGUm1bA",
    link: "/Halaman/page/3/10/11",
    category: "Member Only Live Replay",
  },
  {
    id: "12",
    title: "Quant Live 29 Juli 2025",
    drive: "https://youtu.be/UWpRg-PaHCY",
    link: "/Halaman/page/3/10/12",
    category: "Member Only Live Replay",
  },
  {
    id: "13",
    title: "Quant Live 31 Juli 2025",
    drive: "https://youtu.be/LsnGMz1mEsY",
    link: "/Halaman/page/3/10/13",
    category: "Member Only Live Replay",
  },
  {
    id: "14",
    title: "Quant Live 01 Agu 2025",
    drive: "https://youtu.be/WDsfstCLj3E",
    link: "/Halaman/page/3/10/14",
    category: "Member Only Live Replay",
  },
  {
    id: "15",
    title: "Quant Live 02 Agu 2025",
    drive: "https://youtu.be/OBdcsBA8VO8",
    link: "/Halaman/page/3/10/15",
    category: "Member Only Live Replay",
  },
  {
    id: "16",
    title: "Quant Live 04 Agu 2025",
    drive: "https://youtu.be/9OWnZBwXeiE",
    link: "/Halaman/page/3/10/16",
    category: "Member Only Live Replay",
  },
  {
    id: "17",
    title: "Quant Live 05 Agu 2025",
    drive: "https://youtu.be/65y15LL6pLc?si=GU-AwznAZ_t8ldZD",
    link: "/Halaman/page/3/10/17",
    category: "Member Only Live Replay",
  },
  {
    id: "18",
    title: "Quant Live 11 Agu 2025",
    drive: "https://youtu.be/ppBNHYvnKuY?si=1CGqocWziqBcku1F",
    link: "/Halaman/page/3/10/18",
    category: "Member Only Live Replay",
  },
  {
    id: "19",
    title: "Quant Live 12 Agu 2025",
    drive: "https://youtu.be/3z8phW1DaQo?si=hZ3FL3T9utypt9RZ",
    link: "/Halaman/page/3/10/19",
    category: "Member Only Live Replay",
  },
  {
    id: "20",
    title: "Quant Live 14 Agu 2025",
    drive: "https://youtu.be/DWrBrPRHaac?si=Mhn5OP_Qw2eQmBLa",
    link: "/Halaman/page/3/10/20",
    category: "Member Only Live Replay",
  },
  {
    id: "21",
    title: "Quant Live 16 Agu 2025",
    drive: "https://youtu.be/sFh4HWy74Og?si=wnGY1i2bYjdei9hU",
    link: "/Halaman/page/3/10/21",
    category: "Member Only Live Replay",
  },
  {
    id: "22",
    title: "Quant Live 19 Agu 2025",
    drive: "https://youtu.be/6fNPM5ofTLU?si=hvP0rXx0cLtY7k6U",
    link: "/Halaman/page/3/10/22",
    category: "Member Only Live Replay",
  },
  {
    id: "23",
    title: "Quant Live 24 Agu 2025",
    drive: "https://youtu.be/u1vHOJHJlrs?si=uBEUZnYoX7XcXMPv",
    link: "/Halaman/page/3/10/23",
    category: "Member Only Live Replay",
  },
  {
    id: "24",
    title: "Quant Live 26 Agu 2025",
    drive: "https://youtu.be/4FXRm42GAfA?si=9hX0SzRsumO1qBRl",
    link: "/Halaman/page/3/10/24",
    category: "Member Only Live Replay",
  },
  {
    id: "25",
    title: "Quant Live 28 Agu 2025",
    drive: "https://youtu.be/LCgjRrpPgVM?si=IRfcbAVfCxNXyhRl",
    link: "/Halaman/page/3/10/25",
    category: "Member Only Live Replay",
  },
  {
    id: "26",
    title: "Live Quant, 01 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/vUrc59JICtc?si=dAIkZXIS0EGOJ5en",
    link: "/Halaman/page/3/10/26",
    category: "Member Only Live Replay",
  },
  {
    id: "27",
    title: "Live Quant, 06 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/90i2oMfx8pE?si=Gs5j0Ce19hGvLuj7",
    link: "/Halaman/page/3/10/27",
    category: "Member Only Live Replay",
  },
  {
    id: "28",
    title: "Live Quant, 09 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/K6dKkIuIHx0?si=znDlQwkraB6kerWk",
    link: "/Halaman/page/3/10/28",
    category: "Member Only Live Replay",
  },
  {
    id: "29",
    title: "Live Quant, 12 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/TFMyVhXllEs?si=X1hIvRsipTLZuQT2",
    link: "/Halaman/page/3/10/29",
    category: "Member Only Live Replay",
  },
  {
    id: "30",
    title: "Market Outlook FOMC Meeting, September 17, 2025 - LIVE QUANT - Trad...",
    drive: "https://youtu.be/_VU7AQgorAE?si=Z_FvZUdDX0dPr8UH",
    link: "/Halaman/page/3/10/30",
    category: "Member Only Live Replay",
  },
  {
    id: "31",
    title: "The Quant - Why The Cycle Isnt Over. - Trade With Suli Live",
    drive: "https://youtu.be/9bQDDhdPF7Q?si=bY4zRv8Q9rrBporw",
    link: "/Halaman/page/3/10/31",
    category: "Member Only Live Replay",
  },
];