export const Data = [
  {
    id: "1",
    title: "Foundation of Crypto & Forex - Trade With Suli Modul",
    drive: "https://youtu.be/6o9uAZpDU5Q?si=E0DAb5__zKiaT6LJ",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "2",
    title: "DOW Theory & Basics Of Market - Trade With Suli Modul",
    drive: "https://youtu.be/H-yeabuyO6w?si=b-piSIuf84b59BL5",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "3",
    title: "Crypto Trend Liveclass - Trade With Suli Modul",
    drive: "https://youtu.be/m9mpeECMyxY?si=G_gx5OIm8NwrHu1A",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "4",
    title: "Crypto Candlestick Liveclass - Trade With Suli Modul",
    drive: "https://youtu.be/V6xt433C8L0?si=xvHN7-DIewXL65Ia",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "5",
    title: "Chart Review - Trade With Suli Modul",
    drive: "https://youtu.be/Hp_sxQMuSmQ?si=k_Ldr7SB03yq5CN9",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "6",
    title: "Chart Review - Trade With Suli Modul",
    drive: "https://youtu.be/pok45zJBYBg?si=vdUWLPNd8FJu2dYn",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "7",
    title: "Chart Review #2 - Trade With Suli Modul",
    drive: "https://youtu.be/Uyz6hINw22Y?si=tBzuGRQIwI3zH0dl",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "8",
    title: "Crypto Chart Pattern Liveclass - Trade With Suli Modul",
    drive: "https://youtu.be/J07Y214AfY8?si=xlgKY7yc_DIIcAga",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "9",
    title: "Trading Psychology Liveclass - Trade With Suli Modul",
    drive: "https://youtu.be/UtMLAeys4VY?si=lgy76oJH2yafSuus",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
  {
    id: "10",
    title: "Trading Plan Liveclass - Trade With Suli Modul",
    drive: "https://youtu.be/fDjGHrTek1U?si=EVvD2cem-5GUZWfl",
    link: "/Halaman/page/2/24/1",
    category: "Cara Cari Coin Yang Bisa Naik 10,000%",
  },
];
