export const Data = [
  {
    id: "1",
    title: "Member Only Live Replay Sulianto & Quant, 5 Juni 2025",
    drive: "https://youtu.be/RLvC8K-qTeI?si=VZZx89aqRFQNB-IV",
    link: "/Halaman/page/3/7/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Member Only Live Replay Sulianto, 26 Juni 2025",
    drive: "https://youtu.be/McnmEIY-jWk?si=4Nk5W75ysbHEeEbs",
    link: "/Halaman/page/3/7/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Member Only Live Replay Sulianto, 24 Jul 2025",
    drive: "https://youtu.be/1-6pFZA0aaY",
    link: "/Halaman/page/3/7/3",
    category: "Member Only Live Replay",
  },
  {
    id: "4",
    title: "Member Only Live Replay Sulianto, 31 Jul 2025",
    drive: "https://youtu.be/BMrM57mcsJw",
    link: "/Halaman/page/3/7/4",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Member Only Live Replay Sulianto, 15 Agu 2025",
    drive: "https://youtu.be/7nh-7whagDw?si=YJKUz_JaWTDoZCZR",
    link: "/Halaman/page/3/7/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Member Only Live Replay Sulianto, 25 Agu 2025",
    drive: "https://youtu.be/WFAIo7bMJCA?si=Em_3KWxKqyj398ou",
    link: "/Halaman/page/3/7/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Live Sulianto, 02 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/amol2PrEuSA?si=C8y0PwBbej9VfWdc",
    link: "/Halaman/page/3/7/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Live Sulianto, 11 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/QNJ3j_i_QSo?si=FSx6127X4bucjH0B",
    link: "/Halaman/page/3/7/8",
    category: "Member Only Live Replay",
  },
  {
    id: "9",
    title: "Live Sulianto, 16 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/gGfATMS-_3g?si=ll_JOYBvxSgFmhln",
    link: "/Halaman/page/3/7/9",
    category: "Member Only Live Replay",
  },
  {
    id: "10",
    title: "Live Sulianto, 24 Sep 2025 - Trade With Suli Live",
    drive: "https://youtu.be/2bnpDcpMuUI?si=u8wl_JyE-nZY3rcF",
    link: "/Halaman/page/3/7/9",
    category: "Member Only Live Replay",
  },
  {
    id: "11",
    title: "Live Sulianto, 27 Sep 2025 - Trade With Suli Live",
    drive: "hhttps://youtu.be/SDgg2ISN2WY?si=iygiq29X6JqSapyw",
    link: "/Halaman/page/3/7/9",
    category: "Member Only Live Replay",
  },
];

export const ReversedData = [...Data].reverse();