export const tradingData = [
  {
    title: "On Boarding Premium Membership",
    image: "/images/A1.webp", 
    link: "/Halaman/page/1/1",
    category: "Modul Level 0",
  },
  {
    title: "Personal Finance Blueprint",
    image: "/images/personal-finance-blueprint1.webp",
    link: "/Halaman/page/1/17",
    category: "Modul Level 0",
  },
  {
    title: "Prediksi Q4 Arah Bitcoin & ALtcoin",
    image: "/images/prediksi_q4.webp",
    link: "/Halaman/page/1/16",
    category: "Modul Level 0",
  },
  {
    title: "Decoding The Crypto Cycle - Trade With Suli Modul",
    image: "/images/dicoding_crypto_cycle.webp",
    link: "/Halaman/page/1/15",
    category: "Modul Level 0",
  },
  {
    title: "Eth Supercycle",
    image: "/images/eth-supecycle.webp",
    link: "/Halaman/page/1/14",
    category: "Modul Level 0",
  },
  {
    title: "Cara Recovery",
    image: "/images/cara-re.webp", 
    link: "/Halaman/page/1/13",
    category: "Modul Level 0",
  },
  {
    title: "Bitcoin Zero Sum",
    image: "/images/bitcoin-zero-sum.webp",
    link: "/Halaman/page/1/11",
    category: "Modul Level 0",
  },
  {
    title: "Crypto Fundamentals Guide",
    image: "/images/A2.webp", 
    link: "/Halaman/page/1/2",
    category: "Modul Level 0",
  },
  {
    title: "Cara Memilih Exchange Crypto",
    image: "/images/A3.webp", 
    link: "/Halaman/page/1/3",
    category: "Modul Level 0",
  },
  {
    title: "Leverage 101",
    image: "/images/A4.webp", 
    link: "/Halaman/page/1/4",
    category: "Modul Level 0",
  },
  {
    title: "Cara Pakai Tradingview Dari 0",
    image: "/images/A5.webp", 
    link: "/Halaman/page/1/5",
    category: "Modul Level 0",
  },
  {
    title: "Crypto Judi Atau Investasi",
    image: "/images/A6.webp", 
    link: "/Halaman/page/1/6",
    category: "Modul Level 0",
  },
  {
    title: "Diversification",
    image: "/images/A7.webp", 
    link: "/Halaman/page/1/7",
    category: "Modul Level 0",
  },
  {
    title: "FAQ and Mind Management",
    image: "/images/A8.webp",
    link: "/Halaman/page/1/8",
    category: "Modul Level 0",
  },
  {
    title: "Order Type",
    image: "/images/A9.webp",
    link: "/Halaman/page/1/9",
    category: "Modul Level 0",
  },
  {
    title: "Intro to Web3 Jobs",
    image: "/images/A10.webp",
    link: "/Halaman/page/1/10",
    category: "Modul Level 0",
  },
    {
    title: "Zero To Hero Web3 Jobs",
    image: "/images/zero-to-hero.webp",
    link: "/Halaman/page/1/12",
    category: "Modul Level 0",
  },
];