export const investingData = [
  {
    title: "Suli Crypto Trading Bootcamp",
    image: "/images/suli_crypto_trading_bootcamp.webp", 
    link: "/Halaman/page/2/1",
    category: "Modul Level 1",
  },
  {
    title: "Basic Market",
    image: "/images/B1.webp", 
    link: "/Halaman/page/2/1",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Trading Principle",
    image: "/images/B2.webp", 
    link: "/Halaman/page/2/2",
    category: "Modul Level 1",
  },
  {
    title: "Core Technical Analysis Logic",
    image: "/images/B3.webp", 
    link: "/Halaman/page/2/3",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Trend Guide",
    image: "/images/B4.webp", 
    link: "/Halaman/page/2/4",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Index Guide",
    image: "/images/B5.webp", 
    link: "/Halaman/page/2/5",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Fibonacci Guide",
    image: "/images/B6.webp", 
    link: "/Halaman/page/2/6",
    category: "Modul Level 1",
  },
  {
    title: "Crypto On-Chain Transfer Guide",
    image: "/images/B7.webp", 
    link: "/Halaman/page/2/7",
    category: "Modul Level 1",
  },
  {
    title: "ear Market Strategy",
    image: "/images/B8.webp", 
    link: "/Halaman/page/2/8",
    category: "Modul Level 1",
  },
  {
    title: "Safety Series",
    image: "/images/B9.webp", 
    link: "/Halaman/page/2/9",
    category: "Modul Level 1",
  },
  {
    title: "Web3 Jobs Series: Experienced Interview",
    image: "/images/B10.webp", 
    link: "/Halaman/page/2/10",
    category: "Modul Level 1",
  },
  {
    title: "Money Management on Perp Trading",
    image: "/images/B11.webp", 
    link: "/Halaman/page/2/11",
    category: "Modul Level 1",
  },
  {
    title: "Bahas Geopolitik: Iran vs Israel",
    image: "/images/B12.webp", 
    link: "/Halaman/page/2/12",
    category: "Modul Level 1",
  },
  {
    title: "Probability Game",
    image: "/images/B13.webp", 
    link: "/Halaman/page/2/13",
    category: "Modul Level 1",
  },
  {
    title: "rading Korelasi DCA etc",
    image: "/images/B14.webp", 
    link: "/Halaman/page/2/14",
    category: "Modul Level 1",
  },
  {
    title: "Apakah Bisa Bebas Finansial Lewat Crypto?",
    image: "/images/B15.webp", 
    link: "/Halaman/page/2/15",
    category: "Modul Level 1",
  },
  {
    title: "bias-didunia-investasi",
    image: "/images/bias-didunia-investasi.webp", 
    link: "/Halaman/page/2/17",
    category: "Modul Level 1",
  },
  {
    title: "qunat-performing",
    image: "/images/qunat-performing.webp", 
    link: "/Halaman/page/2/18",
    category: "Modul Level 1",
  },
  {
    title: "Bias Dunia Investasi",
    image: "/images/bias-didunia-investasi.webp", 
    link: "/Halaman/page/2/17",
    category: "Modul Level 1",
  },
  {
    title: "tws-internal",
    image: "/images/tws-internal.webp", 
    link: "/Halaman/page/2/19",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Liquidity Analysis",
    image: "/images/crypto-liuidity-analysis.webp", 
    link: "/Halaman/page/2/20",
    category: "Modul Level 1",
  },
  {
    title: "meme-coin",
    image: "/images/meme-coin.webp", 
    link: "/Halaman/page/2/21",
    category: "Modul Level 1",
  },
  {
    title: "crypto-candel",
    image: "/images/crypto-candel.webp", 
    link: "/Halaman/page/2/22",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Orderblock Analysis",
    image: "/images/crypto-orderblock-analysis.webp", 
    link: "/Halaman/page/2/23",
    category: "Modul Level 1",
  },
  {
    title: "trend-following",
    image: "/images/trend-following.webp", 
    link: "/Halaman/page/2/24",
    category: "Modul Level 1",
  },
];