export const Data = [
  {
    id: "1",
    title: "Live Mira 28 Juni - Weekly Plan",
    drive: "https://youtu.be/rUJT7ZDEjRw?si=-lakgdPMATdg4Ed8",
    link: "/Halaman/page/3/11/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Mira Live Answer Your Question",
    drive: "https://youtu.be/n6V6wxjCPZI?si=YbcZD6RcEFiw5rsg",
    link: "/Halaman/page/3/11/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Mira Live 30 Juni - Daily Plan",
    drive: "https://youtu.be/2dYGO4PBcZY?si=ktGrP-QOheVzLkjg",
    link: "/Halaman/page/3/11/3",
    category: "Member Only Live Replay",
  },
  {
    id: "4",
    title: "Mira Live 2 Juli - Daily Plan",
    drive: "https://youtu.be/BowED-uDyKY?si=hD2mDsvlOVYTptr9",
    link: "/Halaman/page/3/11/4",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Mira Live 5 Juli - Weekly Plan",
    drive: "https://youtu.be/Lg11bPt_v_A?si=eirjQrgGabRldniO",
    link: "/Halaman/page/3/11/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Mira Live 7 Juli - Daily Plan",
    drive: "https://youtu.be/pY07G3gqO9o?si=gwRYhPrSgGlrBa4M",
    link: "/Halaman/page/3/11/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Mira Live 10 Juli - Daily Plan",
    drive: "https://youtu.be/n8WxW0hekAI?si=VqHNoSxWbNMC5JyE",
    link: "/Halaman/page/3/11/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Mira Live 12 Juli - Screening",
    drive: "https://youtu.be/p9DwTQozfG4?si=X-dbeqzVm4JKJ2pV",
    link: "/Halaman/page/3/11/8",
    category: "Member Only Live Replay",
  },
  {
    id: "9",
    title: "Mira Live 14 Juli - Screening",
    drive: "https://youtu.be/zPqTGllyxWo?si=5oFvefWg5mZxU15Z",
    link: "/Halaman/page/3/11/9",
    category: "Member Only Live Replay",
  },
  {
    id: "10",
    title: "Mira Live 17 Juli - Screening",
    drive: "https://youtu.be/6e1HvS5FT6s?si=bXbduxmeC1m4p59V",
    link: "/Halaman/page/3/11/10",
    category: "Member Only Live Replay",
  },
  {
    id: "11",
    title: "Mira Live 20 Juli - Weekly Plan",
    drive: "https://youtu.be/BxaIsLhIGAo?si=ztbCFjO2-cfko-ux",
    link: "/Halaman/page/3/11/11",
    category: "Member Only Live Replay",
  },
  {
    id: "12",
    title: "Mira Live 21 Juli - Daily Plan",
    drive: "https://youtu.be/hFlkiTL4sao?si=EW-KTqYLVe6hd0jY",
    link: "/Halaman/page/3/10/12",
    category: "Member Only Live Replay",
  },
  {
    id: "13",
    title: "Mira Live 24 Juli - Weekly Plan",
    drive: "https://youtu.be/GU8dakyFLWo",
    link: "/Halaman/page/3/11/13",
    category: "Member Only Live Replay",
  },
  {
    id: "14",
    title: "Mira Live 26 Juli - Daily Plan",
    drive: "https://youtu.be/WUVM8QNs40U",
    link: "/Halaman/page/3/10/14",
    category: "Member Only Live Replay",
  },
  {
    id: "15",
    title: "Mira Live 7 Agu - Daily Study",
    drive: "https://youtu.be/uiYtashJ35c?si=mHw-Leh_OBp5d2Aa",
    link: "/Halaman/page/3/10/15",
    category: "Member Only Live Replay",
  },
  {
    id: "16",
    title: "Mira Live 9 Agu - Weakly Plan",
    drive: "https://youtu.be/NrwS8JCsEBc?si=ThXoW8zncGsGE6rx",
    link: "/Halaman/page/3/10/16",
    category: "Member Only Live Replay",
  },
  {
    id: "17",
    title: "Mira Live 11 Agu - Daily Plan",
    drive: "https://youtu.be/X-2RyrjD8ug?si=s_vS3XFZX4os-YVN",
    link: "/Halaman/page/3/10/17",
    category: "Member Only Live Replay",
  },
  {
    id: "18",
    title: "Mira Live 13 Agu - Entry Model",
    drive: "https://youtu.be/IN-w_61OSY4?si=ljiMhBt3kJC4WK79",
    link: "/Halaman/page/3/10/18",
    category: "Member Only Live Replay",
  },
  {
    id: "19",
    title: "Mira Live 17 Agu - Entry Model",
    drive: "https://youtu.be/yjkF69MpZAg?si=_PgxN_AkuntKmSH3",
    link: "/Halaman/page/3/10/19",
    category: "Member Only Live Replay",
  },
  {
    id: "20",
    title: "Mira Live 19 Agu - BTC Update",
    drive: "https://youtu.be/z0znyBFnbO4?si=tLMNfd6GMha0RRCW",
    link: "/Halaman/page/3/10/20",
    category: "Member Only Live Replay",
  },
  {
    id: "21",
    title: "Mira Live 21 Agu - Outlook UpdateStart",
    drive: "https://youtu.be/9qOFRXDw-s4?si=ARcRJg7VEnnHLeK1",
    link: "/Halaman/page/3/10/21",
    category: "Member Only Live Replay",
  },
  {
    id: "22",
    title: "Mira Live 22 Agu - BTC UpdateStart",
    drive: "https://youtu.be/lmRohOu6ZUw?si=g8ltZwLK2HwJBEv5",
    link: "/Halaman/page/3/10/22",
    category: "Member Only Live Replay",
  },
  {
    id: "23",
    title: "Mira Live 22 Agu - Daily PlanStart",
    drive: "https://youtu.be/8FdFboIeq9Y?si=Zk8EjvtBd1bOfB9V",
    link: "/Halaman/page/3/10/23",
    category: "Member Only Live Replay",
  },
  {
    id: "24",
    title: "Mira Live 27 Agu - BTC UpdateStart",
    drive: "https://youtu.be/6fNMnA1zlr0?si=OkxMCN_2E1u3HH1e",
    link: "/Halaman/page/3/10/24",
    category: "Member Only Live Replay",
  },
  {
    id: "25",
    title: "Live Mira, 01 September - Study Footprint",
    drive: "https://youtu.be/ehqsEAhRzVM?si=r2nrWRvpHDZ3Coah",
    link: "/Halaman/page/3/10/25",
    category: "Member Only Live Replay",
  },
  {
    id: "26",
    title: "Live Mira, 8 September - BTC Update",
    drive: "https://youtu.be/nJUpzao-JYY?si=CEkbzbcuwhjpQqYu",
    link: "/Halaman/page/3/10/26",
    category: "Member Only Live Replay",
  },
  {
    id: "27",
    title: "Live Mira, 10 September - Market Outlook - Trade With Suli Live",
    drive: "https://youtu.be/2qTDpVZOCqA?si=JnXJB5S1HPajNX3n",
    link: "/Halaman/page/3/10/27",
    category: "Member Only Live Replay",
  },
  {
    id: "28",
    title: "Live Mira, 14 September - New Module",
    drive: "https://youtu.be/8AsX0fLMzMM?si=kfyP2McR3VK7EIPe",
    link: "/Halaman/page/3/10/28",
    category: "Member Only Live Replay",
  },
  {
    id: "29",
    title: "Live Mira, 17 September - BTC Update - Trade With Suli Live",
    drive: "https://youtu.be/tg-xLmrz_W0?si=9I4y2IAtcAcfeKvI",
    link: "/Halaman/page/3/10/29",
    category: "Member Only Live Replay",
  },
  {
    id: "30",
    title: "Live Mira, 19 September - BTC Update - Trade With Suli Live",
    drive: "https://youtu.be/hXjA2sLBJ_s?si=2SZRNAKknhJxhk39",
    link: "/Halaman/page/3/10/30",
    category: "Member Only Live Replay",
  },
  {
    id: "31",
    title: "Live Mira 22 September - BTC UpdateStart",
    drive: "https://youtu.be/xJlqzRpdmqo?si=UU8iaTa8wPz2fPIl",
    link: "/Halaman/page/3/10/31",
    category: "Member Only Live Replay",
  },
];